import React, { useState } from 'react';
import { 
  Award, 
  CheckCircle2, 
  AlertCircle, 
  Download, 
  RotateCcw, 
  Sparkles, 
  ChevronDown, 
  ChevronUp, 
  BookOpen, 
  BarChart3, 
  FileText,
  Clock,
  Mic,
  ArrowRight,
  BookmarkCheck
} from 'lucide-react';
import { FinalEvaluation } from '../../types/interview';

interface ScorecardViewProps {
  role: string;
  seniority: string;
  interviewType: string;
  evaluation: FinalEvaluation;
  totalDurationSeconds: number;
  fillerWordCounts: Record<string, number>;
  onStartNew: () => void;
  onSaveSession: () => void;
  isSaved?: boolean;
}

export const ScorecardView: React.FC<ScorecardViewProps> = ({
  role,
  seniority,
  interviewType,
  evaluation,
  totalDurationSeconds,
  fillerWordCounts,
  onStartNew,
  onSaveSession,
  isSaved = false
}) => {
  const [expandedQuestionIdx, setExpandedQuestionIdx] = useState<number | null>(0);
  const [downloadSuccess, setDownloadSuccess] = useState<boolean>(false);

  const formatDuration = (secs: number) => {
    const mins = Math.floor(secs / 60);
    const remainingSecs = secs % 60;
    return `${mins}m ${remainingSecs}s`;
  };

  const totalFillers = Object.values(fillerWordCounts).reduce((a, b) => a + b, 0);

  const getVerdictBadge = (verdict: string) => {
    switch (verdict) {
      case 'Strong Hire':
        return 'bg-emerald-500/15 text-emerald-400 border-emerald-500/30';
      case 'Hire':
        return 'bg-blue-500/15 text-blue-400 border-blue-500/30';
      case 'Leaning Hire':
        return 'bg-amber-500/15 text-amber-400 border-amber-500/30';
      default:
        return 'bg-rose-500/15 text-rose-400 border-rose-500/30';
    }
  };

  const handleDownloadReport = () => {
    const reportText = `===================================================
INTERVIEWPULSE AI - POST-INTERVIEW SCORECARD REPORT
===================================================

ROLE: ${seniority} ${role}
TRACK: ${interviewType}
DATE: ${new Date().toLocaleDateString()}
OVERALL SCORE: ${evaluation.overallScore} / 100
HIRING COMMITTEE VERDICT: ${evaluation.verdict}

KEY METRICS:
- STAR Method Structure: ${evaluation.starMethodScore}%
- Technical & Domain Depth: ${evaluation.technicalDepthScore}%
- Communication & Tone: ${evaluation.communicationScore}%
- Confidence & Pacing: ${evaluation.confidencePacingScore}%
- Duration: ${formatDuration(totalDurationSeconds)}
- Total Filler Words: ${totalFillers} (${JSON.stringify(fillerWordCounts)})

EXECUTIVE SUMMARY:
${evaluation.executiveSummary}

TOP STRENGTHS:
${evaluation.topStrengths.map(s => `- ${s}`).join('\n')}

CRITICAL IMPROVEMENT AREAS:
${evaluation.criticalImprovementAreas.map(a => `- ${a}`).join('\n')}

ACTION PLAN:
${evaluation.actionPlan.map(p => `- ${p}`).join('\n')}

QUESTION-BY-QUESTION BREAKDOWN:
${evaluation.questionBreakdowns.map((q, i) => `
---------------------------------------------------
Q${i + 1}: ${q.question}
Score: ${q.score}/100
Candidate Recap: ${q.candidateAnswerSummary}
Strengths: ${q.strengths.join(', ')}
Missing Elements: ${q.missedOpportunities.join(', ')}

Model Ideal Answer (STAR):
${q.modelIdealAnswer}
`).join('\n')}

===================================================
Generated by InterviewPulse AI Simulator
`;

    const blob = new Blob([reportText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `InterviewPulse_${role.replace(/\s+/g, '_')}_Scorecard.txt`;
    a.click();
    URL.revokeObjectURL(url);

    setDownloadSuccess(true);
    setTimeout(() => setDownloadSuccess(false), 3000);
  };

  return (
    <div className="max-w-5xl mx-auto px-4 py-8 text-white space-y-8">
      {/* Top Banner / Hero Verdict */}
      <div className="bg-slate-900/90 border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-2xl backdrop-blur-md relative overflow-hidden">
        {/* Glow backdrop */}
        <div className="absolute top-0 right-0 w-96 h-96 bg-blue-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6 pb-6 border-b border-slate-800">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="text-xs font-semibold uppercase tracking-wider text-slate-400">
                Evaluation Complete
              </span>
              <span className="text-slate-600">·</span>
              <span className="text-xs text-blue-400 font-medium">
                {seniority} {role}
              </span>
            </div>
            <h1 className="text-2xl sm:text-4xl font-extrabold text-white tracking-tight">
              Post-Interview Bar Raiser Scorecard
            </h1>
            <p className="text-sm text-slate-400 mt-1 max-w-xl">
              Comprehensive performance debrief calibrated against standard hiring committee benchmarks.
            </p>
          </div>

          {/* Hiring Verdict Badge */}
          <div className="text-left md:text-right shrink-0">
            <span className="text-xs text-slate-400 uppercase tracking-wider block mb-1 font-mono">
              Committee Verdict
            </span>
            <span className={`inline-block px-4 py-1.5 rounded-xl text-base sm:text-lg font-extrabold border shadow-lg ${getVerdictBadge(evaluation.verdict)}`}>
              {evaluation.verdict}
            </span>
          </div>
        </div>

        {/* 4 Score Metrics Grid */}
        <div className="grid grid-cols-2 lg:grid-cols-5 gap-4 pt-6">
          {/* Overall Big Score */}
          <div className="col-span-2 lg:col-span-1 p-4 rounded-2xl bg-gradient-to-br from-blue-600/20 to-indigo-600/10 border border-blue-500/30 flex flex-col items-center justify-center text-center">
            <span className="text-xs text-blue-300 font-medium uppercase font-mono">Overall Score</span>
            <div className="text-4xl sm:text-5xl font-black text-white mt-1 tracking-tight">
              {evaluation.overallScore}
              <span className="text-base text-blue-400 font-normal">/100</span>
            </div>
            <span className="text-[11px] text-blue-200 mt-1">Weighted Composite</span>
          </div>

          {/* Sub Score: STAR Method */}
          <div className="p-4 rounded-2xl bg-slate-950/70 border border-slate-800">
            <span className="text-xs text-slate-400 font-medium block">STAR Structure</span>
            <div className="text-2xl font-bold text-white mt-1">
              {evaluation.starMethodScore}%
            </div>
            <div className="w-full bg-slate-800 h-1 rounded-full mt-2 overflow-hidden">
              <div className="bg-blue-500 h-full rounded-full" style={{ width: `${evaluation.starMethodScore}%` }} />
            </div>
          </div>

          {/* Sub Score: Technical Depth */}
          <div className="p-4 rounded-2xl bg-slate-950/70 border border-slate-800">
            <span className="text-xs text-slate-400 font-medium block">Technical Depth</span>
            <div className="text-2xl font-bold text-white mt-1">
              {evaluation.technicalDepthScore}%
            </div>
            <div className="w-full bg-slate-800 h-1 rounded-full mt-2 overflow-hidden">
              <div className="bg-indigo-500 h-full rounded-full" style={{ width: `${evaluation.technicalDepthScore}%` }} />
            </div>
          </div>

          {/* Sub Score: Communication */}
          <div className="p-4 rounded-2xl bg-slate-950/70 border border-slate-800">
            <span className="text-xs text-slate-400 font-medium block">Communication</span>
            <div className="text-2xl font-bold text-white mt-1">
              {evaluation.communicationScore}%
            </div>
            <div className="w-full bg-slate-800 h-1 rounded-full mt-2 overflow-hidden">
              <div className="bg-cyan-500 h-full rounded-full" style={{ width: `${evaluation.communicationScore}%` }} />
            </div>
          </div>

          {/* Sub Score: Confidence & Pacing */}
          <div className="p-4 rounded-2xl bg-slate-950/70 border border-slate-800">
            <span className="text-xs text-slate-400 font-medium block">Pacing & Flow</span>
            <div className="text-2xl font-bold text-white mt-1">
              {evaluation.confidencePacingScore}%
            </div>
            <div className="w-full bg-slate-800 h-1 rounded-full mt-2 overflow-hidden">
              <div className="bg-emerald-500 h-full rounded-full" style={{ width: `${evaluation.confidencePacingScore}%` }} />
            </div>
          </div>
        </div>

        {/* Audio Delivery Stats HUD */}
        <div className="mt-4 pt-4 border-t border-slate-800/80 flex flex-wrap items-center justify-between gap-4 text-xs text-slate-400">
          <div className="flex items-center gap-6">
            <span className="flex items-center gap-1.5">
              <Clock className="w-4 h-4 text-slate-500" />
              Duration: <strong className="text-slate-200">{formatDuration(totalDurationSeconds)}</strong>
            </span>

            <span className="flex items-center gap-1.5">
              <Mic className="w-4 h-4 text-slate-500" />
              Filler Words: <strong className={`font-semibold ${totalFillers > 5 ? 'text-amber-400' : 'text-emerald-400'}`}>{totalFillers}</strong>
            </span>
          </div>

          <p className="text-xs text-slate-400 italic">
            "{evaluation.pacingFeedback}"
          </p>
        </div>
      </div>

      {/* Executive Summary */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl backdrop-blur-sm">
        <h2 className="text-base font-semibold text-white mb-2 flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-blue-400" />
          Hiring Committee Consensus
        </h2>
        <p className="text-sm text-slate-300 leading-relaxed">
          {evaluation.executiveSummary}
        </p>
      </div>

      {/* Top Strengths & Critical Improvements */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {/* Strengths */}
        <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl backdrop-blur-sm">
          <div className="flex items-center gap-2 mb-4 text-emerald-400">
            <CheckCircle2 className="w-5 h-5" />
            <h3 className="font-bold text-sm text-white">Standout Strengths</h3>
          </div>
          <ul className="space-y-2.5">
            {evaluation.topStrengths.map((str, idx) => (
              <li key={idx} className="text-xs sm:text-sm text-slate-300 flex items-start gap-2 leading-relaxed">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-2 shrink-0" />
                <span>{str}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Critical Improvement Areas */}
        <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl backdrop-blur-sm">
          <div className="flex items-center gap-2 mb-4 text-amber-400">
            <AlertCircle className="w-5 h-5" />
            <h3 className="font-bold text-sm text-white">Critical Focus Areas</h3>
          </div>
          <ul className="space-y-2.5">
            {evaluation.criticalImprovementAreas.map((imp, idx) => (
              <li key={idx} className="text-xs sm:text-sm text-slate-300 flex items-start gap-2 leading-relaxed">
                <span className="w-1.5 h-1.5 rounded-full bg-amber-400 mt-2 shrink-0" />
                <span>{imp}</span>
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* Question-by-Question Deep Dive */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl backdrop-blur-sm">
        <h2 className="text-base font-semibold text-white mb-4 flex items-center justify-between">
          <span className="flex items-center gap-2">
            <FileText className="w-4 h-4 text-blue-400" />
            <span>Question-by-Question Analysis & Model Answers</span>
          </span>
          <span className="text-xs font-normal text-slate-400">
            Click question to expand gold standard answer
          </span>
        </h2>

        <div className="space-y-3">
          {evaluation.questionBreakdowns.map((q, idx) => {
            const isExpanded = expandedQuestionIdx === idx;
            return (
              <div
                key={idx}
                className="rounded-xl border border-slate-800 bg-slate-950/60 overflow-hidden transition-all"
              >
                {/* Accordion header */}
                <button
                  type="button"
                  onClick={() => setExpandedQuestionIdx(isExpanded ? null : idx)}
                  className="w-full p-4 text-left flex items-start justify-between gap-4 hover:bg-slate-800/40 transition-colors"
                >
                  <div className="space-y-1">
                    <div className="flex items-center gap-2">
                      <span className="text-xs font-bold text-blue-400 font-mono">Q{idx + 1}</span>
                      <span className="text-xs font-semibold px-2 py-0.5 rounded bg-slate-800 text-slate-300">
                        Score: {q.score}/100
                      </span>
                    </div>
                    <p className="font-medium text-sm text-white leading-snug">
                      "{q.question}"
                    </p>
                  </div>

                  <div className="shrink-0 text-slate-400">
                    {isExpanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                  </div>
                </button>

                {/* Expanded Details */}
                {isExpanded && (
                  <div className="p-4 pt-0 border-t border-slate-800/60 space-y-4 text-xs">
                    {/* Candidate Answer Recap */}
                    <div className="p-3 rounded-lg bg-slate-900/80 border border-slate-800/80">
                      <p className="font-semibold text-slate-400 text-[11px] uppercase tracking-wider mb-1">
                        Your Response Summary:
                      </p>
                      <p className="text-slate-200 italic leading-relaxed">
                        "{q.candidateAnswerSummary}"
                      </p>
                    </div>

                    {/* Strengths & Missing Points */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      <div className="p-3 rounded-lg bg-emerald-500/5 border border-emerald-500/20">
                        <p className="font-semibold text-emerald-400 mb-1">What Worked:</p>
                        <ul className="space-y-1 text-slate-300">
                          {q.strengths.map((s, i) => (
                            <li key={i}>• {s}</li>
                          ))}
                        </ul>
                      </div>

                      <div className="p-3 rounded-lg bg-amber-500/5 border border-amber-500/20">
                        <p className="font-semibold text-amber-400 mb-1">What Was Missing:</p>
                        <ul className="space-y-1 text-slate-300">
                          {q.missedOpportunities.map((m, i) => (
                            <li key={i}>• {m}</li>
                          ))}
                        </ul>
                      </div>
                    </div>

                    {/* Benchmark Gold-Standard Answer */}
                    <div className="p-3.5 rounded-xl bg-blue-500/10 border border-blue-500/30 text-slate-200">
                      <div className="flex items-center gap-1.5 font-bold text-blue-300 mb-1.5">
                        <Sparkles className="w-3.5 h-3.5 text-blue-400" />
                        <span>Gold Standard Model Answer (STAR Benchmark 98/100):</span>
                      </div>
                      <p className="text-xs text-blue-100 leading-relaxed whitespace-pre-line">
                        {q.modelIdealAnswer}
                      </p>
                    </div>
                  </div>
                )}
              </div>
            );
          })}
        </div>
      </div>

      {/* Action Plan */}
      <div className="bg-slate-900/80 border border-slate-800 rounded-2xl p-6 shadow-xl backdrop-blur-sm">
        <h2 className="text-base font-semibold text-white mb-3 flex items-center gap-2">
          <BookOpen className="w-4 h-4 text-blue-400" />
          Recommended 3-Step Practice Roadmap
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          {evaluation.actionPlan.map((plan, i) => (
            <div key={i} className="p-3.5 rounded-xl bg-slate-950/70 border border-slate-800 text-xs text-slate-300">
              <span className="w-5 h-5 rounded-md bg-blue-600/20 text-blue-400 font-bold flex items-center justify-center mb-2 border border-blue-500/30">
                {i + 1}
              </span>
              <p className="leading-relaxed">{plan}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Action CTA Buttons */}
      <div className="flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-slate-800">
        <div className="flex items-center gap-3">
          <button
            onClick={handleDownloadReport}
            className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-semibold text-xs border border-slate-700 transition-colors flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            <span>{downloadSuccess ? 'Report Downloaded!' : 'Export Scorecard (TXT)'}</span>
          </button>

          <button
            onClick={onSaveSession}
            disabled={isSaved}
            className={`px-4 py-2.5 rounded-xl font-semibold text-xs border transition-colors flex items-center gap-2 ${
              isSaved
                ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-400'
                : 'bg-slate-800 hover:bg-slate-700 text-white border-slate-700'
            }`}
          >
            <BookmarkCheck className="w-4 h-4" />
            <span>{isSaved ? 'Saved to History' : 'Save Session'}</span>
          </button>
        </div>

        <button
          onClick={onStartNew}
          className="px-6 py-2.5 rounded-xl font-bold text-xs bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white shadow-lg shadow-blue-500/25 active:scale-[0.98] transition-all flex items-center gap-2"
        >
          <RotateCcw className="w-4 h-4" />
          <span>Start New Interview Simulation</span>
        </button>
      </div>
    </div>
  );
};
